### ISSUE TITLE
Querying missing localization data doesn't work

### ISSUE THREAD

**Issue by jasonvarga** [statamic/eloquent-driver#112]
On localized entries, any fields that you don't choose to localize will fall back to what's in the origin. That's fine.

However if you try to perform a query on one of these fields, the localized versions will not appear.

For example: (using yaml to represent the rows, obviously in eloquent it's stored differently)

```yaml
id: 1
title: Origin entry
foo: bar
```

```yaml
id: 2
origin_id: 1
title: Localized entry
# foo is intentionally missing, because we want it to fall back to bar
```

```php
Entry::query()->where('foo', 'bar')->get(); // only returns the origin entry
```

In the Stache driver it works fine because the indexes/columns are generated on the fly.

An idea: store _all_ the data so it's queryable, but also store something like `localized_keys` so we can work out what goes in `$entry->data()` when we build the objects.
