### ISSUE TITLE
Unable to reorder collection

### ISSUE THREAD

**Issue by jorisvan-ons** [statamic/eloquent-driver#150]
Reordering seems bugged. The values are coming through in the correct order when inspecting the `$reorderedEntries->values()->all()` in the `ReorderEntriesController`.

However, the table is reloaded and the values are back in the old order again. The database 'order' columns to not seem to be updated. Manually changing the order columns does work.

**Comment by ryanmitchell** [comment]
Can you run `php please support:details` and paste the result here?

**Comment by jorisvan-ons** [comment]
`Environment
Application Name: CENSORED
Laravel Version: 9.52.6
PHP Version: 8.2.3
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: CENSORED
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO

Statamic Addons
doublethreedigital/runway: 4.2.4
mitydigital/iconamic: 1.1.4
octoper/statamic-blade-components: 2.0.0
statamic/eloquent-driver: 1.2.0`

**Comment by ryanmitchell** [comment]
Thanks. Nothing is jumping out at me there. 
Is your collection dated as well as order able? I wonder if this fix might help: https://github.com/statamic/eloquent-driver/pull/138

**Comment by jorisvan-ons** [comment]
No, the collection is not dated. The date fields are all set to NULL in the database.

**Comment by jorisvan-ons** [comment]
Here is the yaml file of the collection
```
title: Products
template: products/show
layout: layouts/app
revisions: false
route: '/products/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
structure:
  root: false
  max_depth: 1

```
