### ISSUE TITLE
uri column not populated when using split mode+non-sync queue connection

### ISSUE THREAD

**Issue by andreasbohman** [statamic/eloquent-driver#200]
When using file for collection config and eloquent for tree+entries (I've seen it referenced as "split mode" in other issues), we've come across a bit of a weird bug. In combination with using something else than `sync` for queue connection (I've tested with both redis and database), the `uri` column does not get populated on the inital save when creating an entry. We first noticed it recently after upgrading from 1.x, and kept getting 404s for new entries.

To reproduce I did this:
1. Configure Redis locally
2. Fresh install of Statamic 4.20.0
3. In .env-file, set `QUEUE_CONNECTION=redis`
4. Install eloquent-driver 2.6.1, following the instructions for incremental IDs
5. in `config/statamic/eloquent-driver.php`, set `collections.driver` to `file`
6. Configure a collection as orderable (full yaml below)
7. Create a new entry, mark as published and Save & Publish
8. Try to access the entry on the site, it returns a 404.

Collection config `pagez.yaml`:
```
title: Pagez
template: default
layout: layout
revisions: false
route: '{parent_uri}/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: true
```

Sidenote: I did have to create the tree manually in the database in order to avoid the bug described in #198, but that seems unrelated to this bug.

Also, it does not seem to occur when using revisions.

We're having trouble pinpointing where this issue might be occuring, so any help on this is greatly appreciated. Thanks in advance, and thanks for all the great work being done with this package.
