### ISSUE TITLE
Settings a focus point on an asset stored in db errors in the control panel

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/eloquent-driver#239]
### Bug description

I have assets stored in an S3 bucket that are hooked up to eloquent.

When I try set the focus of an asset in the cp, I run into

```
foreach() argument must be of type array|object, string given 
```

### How to reproduce

1. Setup eloquent driver
2. migrate assets
3. select an asset in an entry
4. try set the focal point
5. save the asset
6. see the error

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.43.0
PHP Version: 8.2.15
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: harveststatamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Sites: 4 (Harvest Glasgow, Harvest Ayr, Rooted Conference, Rooted Churches)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.48.0 PRO

Statamic Addons
statamic/eloquent-driver: 3.0.5

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Taxonomies: file
Terms: file
```
```


### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

### Additional details

_No response_
