### ISSUE TITLE
Asset gets duplicated when trying to delete using the proposed eloquent-driver 

### ISSUE THREAD

**Issue by shawinigan** [statamic/eloquent-driver#247]
### Bug description

When we delete an asset, it gets deleted but a new entry is created in the database with the same informations as the deleted assets but with the meta field containing only {"data": []}. The asset stays in the container, showing a size of 0 B and a last modification date of 54 years ago.

### How to reproduce

1. Use the eloquent-driver to save in the database instead of flat file
2. Add an asset in a container
3. check the id of this asset in the database
4. delete the asset
5. see in the database the asset is still there but with a new id

### Environment

```yaml
Environment
Application Name: Intranet
Laravel Version: 10.45.1
PHP Version: 8.1.7
Composer Version: 2.3.7
Environment: local
Debug Mode: ENABLED
URL: localhost:8000
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: pgsql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.49.0 PRO

Statamic Addons
aerni/factory: 1.4.0
eminos/statamic-iconify: 1.0.0
ndx/statamic-bard-color-picker: 1.2.0
statamic-rad-pack/meilisearch: 3.2.1
statamic/eloquent-driver: 3.1.2
tv2regionerne/statamic-image-cropper: 1.4.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
