### ISSUE TITLE
Serialization of 'PDO' is not allowed, when using eloquent assets in a no cache region

### ISSUE THREAD

**Issue by byron-roots** [statamic/eloquent-driver#291]
### Bug description

I've been trying to migrate our assets to eloquent, but when using assets in a nocache region we get an error `Serialization of 'PDO' is not allowed` 

Below is the template we use and removing nocache tags fixes the issue

```antlers
{{ nocache }}
    <div class="c-basket">
        <button class="c-basket__button" @click="open('basket')">
            {{ svg src="basket" }}
                <span class="c-basket__count">
                    {{ sc:cart:quantityTotal }}
                </span>
        </button>
        <template x-teleport="body" >
            <div class="c-basket__portal"
                 x-show="isOpen('basket')"
                 x-transition.500ms
                 x-cloak
                 @click.outside="close()"
                 x-trap.noscroll="isOpen('basket') && isMobile()">
                <div class="c-basket-modal">
                    <div class="c-basket-modal__container">
                        {{ if { sc:cart:quantityTotal } !== 0 }}
                            <div class="c-basket-modal__items">
                                {{ sc:cart:items }}
                                    {{ partial:products.partials.basket }}
                                {{ /sc:cart:items }}
                                <div class="c-basket-modal__totals">
                                    <span class="c-basket-modal__total">{{ trans:newby.total }}</span>
                                    <span class="c-basket-modal__total">{{ sc:cart:total }}</span>
                                </div>
                                <div class="c-basket-modal__actions">
                                    <a href="/cart" class="c-button c-button--purple c-button--large">
                                        {{ trans:newby.view_cart }} ({{ sc:cart:total }})
                                    </a>
                                    <a href="/checkout" class="c-button c-button--orange c-button--large">
                                        {{ trans:newby.continue_checkout }}
                                        {{ svg src="arrow-right" }}
                                    </a>
                                </div>
                            </div>
                        {{ else }}
                            <div class="c-basket-modal__empty">
                                {{ trans:newby.empty_basket }}
                            </div>
                            <div class="c-basket-modal__actions">
                                <a href="{{ mount_url handle="products" }}" class="c-button c-button--orange c-button--large">
                                    {{ trans:newby.shop_products }}
                                    {{ svg src="arrow-right" }}
                                </a>
                            </div>
                        {{ /if }}
                    </div>
                </div>
            </div>
        </template>
    </div>
{{ /nocache }}

```

### How to reproduce

1. Setup new project
2. Use eloquent assets
3. Create template which uses assets and a nocache tag

### Logs

```shell
https://flareapp.io/share/NPGYZMn5
```

### Environment

```yaml
Environment
Application Name: Newby Leisure
Laravel Version: 10.48.11
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: newbyleisure.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Locales
Installed
Locales Version: 1.9.0
Protected

Localization
Installed: en, es
LaravelLang\Attributes\Plugin: 2.10.5
LaravelLang\HttpStatuses\Plugin: 3.8.3
LaravelLang\Lang\Plugin: 13.12.0
Protected Locales: en
Publisher Version: 14.7.1

Simple Commerce
Currencies: GBP, EUR
Gateways: Stripe, Invoice
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\UserCustomerRepository
Repository: Order: App\Repositories\EloquentEntryOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Free Shipping
Tax Engine: DuncanMcClean\SimpleCommerce\Tax\BasicTaxEngine

Livewire
Livewire: v3.4.12

Statamic
Addons: 15
Sites: 2 (English,, Spanish)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.4.0 PRO

Statamic Addons
appswithlove/statamic-one-click-content-translation: 5.2.1
duncanmcclean/simple-commerce: 7.2.0
jacksleight/statamic-bard-texstyle: 3.2.2
jonassiewertsen/statamic-livewire: 3.3.1
markkravchuk/statamic-activity-book: 1.0.1
nineteensquared/instagram: 1.2.0
rootstudio/cache-primer: 0.12
rootstudio/monitor: 0.3
rootstudio/mux-video: 0.6
rootstudio/turnstile: 0.3
statamic-rad-pack/meilisearch: 3.3.0
statamic-rad-pack/runway: 7.1.0
statamic/collaboration: 1.0.0
statamic/eloquent-driver: 4.0.0
stillat/relationships: 2.2.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: file
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: file
Revisions: eloquent
Taxonomies: file
Terms: eloquent
```

**Comment by ryanmitchell** [comment]
What makes you sure it's the assets? It seems youre using eloquent globals and they are in your template too - it could be them.

**Comment by byron-roots** [comment]
As soon as I swap assets to file based it works. 

It could be a combination of both which I can have a go at testing

**Comment by ryanmitchell** [comment]
Are you able to add a dd($region) here so I can inspect the data its attempting to store?

https://github.com/statamic/cms/blob/df7412095459999e59b87eaeff07ab8f804acaae/src/StaticCaching/NoCache/Session.php#L153

**Comment by ryanmitchell** [comment]
What about adding select="zzz|yyy" to the region so you only store the data you need?

**Comment by byron-roots** [comment]
That doesn't have an effect. Even a region without any variables throws the error

```
Statamic\StaticCaching\NoCache\StringRegion {#18163 ▼ // vendor/statamic/cms/src/StaticCaching/NoCache/Session.php:153
  #key: "14264ae7f4a8d2243427655ee00d70c17e3c567e5d48317a123dd7fb6e3c333cfc3bf221"
  #context: []
  #session: 
Statamic\StaticCaching\NoCache
\
Session {#3236 ▶}
  #content: "<p>No content</p>"
  #extension: "antlers.html"
}
```

**Comment by ryanmitchell** [comment]
I can't see any reason for this - @duncanmcclean do you have any ideas?

**Comment by duncanmcclean** [comment]
I don't have any ideas off the top of my head. I'd probably need to have a dig around to figure out what's causing it.

@byron-roots Are you able to share access to the repo or reproduce the issue on a fresh Statamic site?

**Comment by byron-roots** [comment]
I can't add you to the repository, could I send it as a support ticket?

**Comment by duncanmcclean** [comment]
> I can't add you to the repository, could I send it as a support ticket?

Sure, you can send it in as a support request: https://statamic.com/support

**Comment by duncanmcclean** [comment]
I've done a little bit of digging. From what I can tell, it seems like it has something to do with the `media` field on your `shared_content` global.

In the blueprint, the field looks like this, just a normal assets field:

```yaml
-
  handle: media
  field:
    mode: list
    container: assets
    restrict: false
    allow_uploads: true
    show_filename: true
    show_set_alt: true
    type: assets
    display: Media
    icon: assets
    listable: hidden
    instructions_position: above
    visibility: visible
    hide_display: false
```

In the `hotlinks/default.antlers.html` partial, it's looping through the `hotlinks` field on the `shared_content` global:

```antlers
{{ shared_content:hotlinks }}
    <div class="c-hotlinks__item">
        {{ partial:general.article article_class="c-article--center" :article_image="media" }}
    </div>
{{ /shared_content:hotlinks }}
```

If I comment out the `{{ partial }}` bit, or even just remove the `article_image` parameter that's being passed in, the error goes away and the page loads normally.

When I `ray()` the context before it gets [passed into the nocache region here](https://github.com/statamic/cms/blob/20383f531ad64a09c22d631dace4797758ff34f4/src/StaticCaching/NoCache/Tags.php#L35), this is what the `view` array looks like:

![CleanShot 2024-05-23 at 17 17 38](https://github.com/statamic/eloquent-driver/assets/19637309/9c965759-9fbf-412c-af3e-62cddc1c0ffd)

I need to head off now but wanted to leave some notes here for future me or someone else who ends up looking into this.
