### ISSUE TITLE
S3 assets not appearing when assets are in the db but containers are not

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/eloquent-driver#294]
### Bug description

I wanted to keep the config for asset containers in flat files rather than them be eloquent models.

When I do this though, the container shows as having no assets.

### How to reproduce

in `eloquent-driver.php`

```
'assets' => [
        'driver' => 'eloquent',
        'model' => \Statamic\Eloquent\Assets\AssetModel::class,
        'asset' => \Statamic\Eloquent\Assets\Asset::class,
    ],
```

keep `asset_containers` as file.

migrate the assets only

see the container is empty

### Environment

```yaml
Environment
Application Name: Wild at Heart Local Platform
Laravel Version: 10.48.12
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: wahlocal.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Scout: algolia
Session: file

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 3.8.2
PHP SDK Version: 3.22.1
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 1
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.6.1 PRO

Statamic Addons
statamic/eloquent-driver: 4.0.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: file
Revisions: file
Taxonomies: file
Terms: eloquent
```
```


### Additional details

_No response_
