### ISSUE TITLE
Sync command resets all assets previous data

### ISSUE THREAD

**Issue by sdussaut** [statamic/eloquent-driver#298]
### Bug description

Hi!
I am using the eloquent driver with assets enabled. Assets are added outside of Statamic.
When new assets come in, the sync command `php please eloquent:sync-assets` removes all previous data set on all of the already present assets.

### How to reproduce

- Add an asset in the public/assets folder
- Run `php please eloquent:sync-assets` to add it to database
- Go to the control panel and add an alt for the newly added asset.
- Add another asset to the public/assets folder
- Run `php please eloquent:sync-assets` to add it to database
- Go to cp to the first asset, the alt is now empty.

### Environment

```yaml
Environment
Application Name: Test app
Laravel Version: 11.10.0
PHP Version: 8.3.3
Composer Version: 2.6.6
Environment: local
Debug Mode: ENABLED
URL: test-app.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: EUR, EUR
Gateways: Dummy
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DuncanMcClean\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Free Shipping
Tax Engine: DuncanMcClean\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 3
Sites: 2 ([FR] Français, [EN] Anglais)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.2 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.3.0
duncanmcclean/simple-commerce: 7.3.0
statamic/eloquent-driver: 4.2.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```

### Additional details

I am unsure as if this is the intended behaviour or not. The documentation specifies that it will "add any **missing** files to the database" (emphasis is mine) not override all of them :-) 
Am I missing something? A flag to pass to the command to control this behaviour maybe?

Thanks!
