### ISSUE TITLE
Unable to order select options in a blueprint when using eloquent driver

### ISSUE THREAD

**Issue by Baumi-Dev** [statamic/eloquent-driver#312]
### Bug description

When using eloquent driver, the form input options are stored as JSON data, which doesn't allow for specific ordering. Options should be stored in an array to allow for specific ordering

### How to reproduce

Ordering options in flat files works fine, but when using eloquent driver, options are stored in a JSON object, causing the options to be stored in ascending order. Reordering options in the control panel doesn't work, as the options are always stored in ascending order

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.10.0
PHP Version: 8.2.10
Composer Version: 2.7.2
Environment: local
Debug Mode: ENABLED
URL: empower-eats.public.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.11.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.5.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```
