### ISSUE TITLE
Importing pages collection entries misses uri

### ISSUE THREAD

**Issue by webcodecs** [statamic/eloquent-driver#325]
### Bug description

Hey folks,
i want to switch from classic file based data to a database. Everything is working fine, since i noticed that the uri is missing in the database for pages entries. Am i missing some step? I dont know and hope you can give me a hint.

### How to reproduce

Migrating entries from the pages collection with `php artisan statamic:eloquent:import-entries` from file to database

### Environment

```yaml
Environment
Application Name: Hosting
Laravel Version: 10.48.16
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: webgo-api.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: sqlite
Logs: daily
Mail: smtp
Queue: redis
Session: redis

Filament
Packages: forms, notifications, support
Version: v3.2.93
Views: NOT PUBLISHED

Livewire
Livewire: v3.5.4

Sentry
Enabled: YES
Environment: local
Laravel SDK Version: 4.7.0
PHP SDK Version: 4.8.1
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 100%
Sample Rate Profiling: 100%
Send Default PII: DISABLED

Statamic
Addons: 8
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.14.0 PRO

Statamic Addons
duncanmcclean/static-cache-manager: 4.0.0
jonassiewertsen/statamic-livewire: 3.6.0
mitydigital/statamic-scheduled-cache-invalidator: 2.0.5
statamic/eloquent-driver: 4.9.0
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 4.4.0
studio1902/statamic-peak-seo: 8.15.3
studio1902/statamic-peak-tools: 4.4.2

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```
```


### Additional details

_No response_
