### ISSUE TITLE
Unable to get the blueprints to map to columns

### ISSUE THREAD

**Issue by michaeljhopkins** [statamic/eloquent-driver#338]
### Bug description

I'm a little confused how to get the mapped columns to work. My config file looks like the below, the left out code is copied from the default config. Do I need to make the migration myself to get the new columns created? Is there an example of what each `fieldtype` -> `column type` is mapped as?

I am installing this package fresh on a new app so I can modify/delete whatever is easiest

```

   # .........

    'blueprints' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Fields\BlueprintModel::class,
        'namespaces' => 'all',
    ],

   # .........

    'entries' => [
        'driver' => 'eloquent',
        'model' => \Statamic\Eloquent\Entries\UuidEntryModel::class,
        'entry' => \Statamic\Eloquent\Entries\Entry::class,
        'map_data_to_columns' => true,
    ],

   # .........
```

### How to reproduce

```
php statamic:eloquent:import-entries
```

### Environment

```yaml
Environment
Application Name: Statamic Peak
Laravel Version: 11.20.0
PHP Version: 8.3.10
Composer Version: 2.7.5
Environment: local
Debug Mode: ENABLED
URL: 127.0.0.1:8000
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.4

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.7.0
PHP SDK Version: 4.8.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: ENABLED

Statamic
Addons: 5
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.20.0 PRO

Statamic Addons
arthurperton/popular: 1.1.0
jonassiewertsen/statamic-livewire: 3.6.0
reachweb/statamic-livewire-filters: 2.0.0
statamic/eloquent-driver: 4.12.3
tv2regionerne/statamic-reverse-relationship: 1.6.1

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```
