### ISSUE TITLE
Timeout when using TermFieldtype antlers tag

### ISSUE THREAD

**Issue by swen4** [statamic/eloquent-driver#343]
### Bug description

When trying to query terms from a Terms Field in Antlers, my application times out. I have taxonomies and terms configured to use the eloquent driver in my `config/statamic/eloquent-driver.php` file. 

The terms work fine in the control panel, it's only when I try to query the terms through Antlers that the issue arises.

When I revert the eloquent-driver for Terms to "file" the issue doesn't happen.

### How to reproduce

1. Create a taxonomy "Themes" and attach it to a collection.
2. Create a "Theme" called "Example".
3. Create an Antlers template for a single entry, and attempt to display the "Example" theme.

```
{{ themes }}
    {{ title }}
{{ /themes }}
```

5. Configure eloquent driver for "terms" in `config/statamic/eloquent-driver.php`.
6. Run migration for Taxonomies and Terms tables.
7. Run `php please eloquent:import-taxonomies` and "yes" to both prompts
8. Check entry page again, it now times out.

### Logs

```shell
[26-Aug-2024 13:02:37 UTC] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /Users/swen/Projects/statamic/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Casts/Json.php on line 36
[26-Aug-2024 13:02:37 UTC] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32768 bytes) in /Users/swen/Projects/statamic/vendor/symfony/error-handler/Error/FatalError.php on line 1
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.21.0
PHP Version: 8.2.22
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF
Timezone: UTC
Locale: nl

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.5.6

Statamic
Addons: 7
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.23.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.6.0
rias/statamic-redirect: 3.7.2
statamic-rad-pack/runway: 7.8.0
statamic/eloquent-driver: 4.13.0
statamic/seo-pro: 6.0.3
superinteractive/statamic-super-link: 1.0.1
superinteractive/statamic-super-polls: dev-main

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: file
Navigations: file
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: eloquent
```
