### ISSUE TITLE
Can't use status filter for Graphql

### ISSUE THREAD

**Issue by thomas4Bitcraft** [statamic/eloquent-driver#347]
### Bug description

I have just recently switched to the eloquent driver. The problem is, that previously I fetched existing entries for my preview-page like this:

```
query page {
  entry(
    collection: "pages"
    id: "c2980164-0e9b-432b-9658-56d30775ca0d",
    , filter: {status: {regex: "(draft|published|scheduled)"}}
  ) {
    ... on Entry_Pages_Page {
      id
      status
    }
  }
}
```

But as I saw on [this issue](https://github.com/statamic/eloquent-driver/issues/289) the status filter only accepts a filter like `status: {equals: "draft"}`, which means I would have to make 3 different requests to fetch a single page. Is there any other possibility to handle different status values for collections?

### How to reproduce

Switch to eloquent-driver and use the grapqhl status filter

### Environment

```yaml
Environment
Application Name: Website
Laravel Version: 10.48.20
PHP Version: 8.2.7
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: /
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 3.8.2
PHP SDK Version: 3.22.1
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 0%
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 5
Sites: 12 (de, it, en, and 9 more)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.23.0 PRO

Statamic Addons
bitcraft/form-webhook: dev-production
bitcraft/page-generator: dev-production
bitcraft/simple-seo: dev-production
ndx/statamic-bard-color-picker: 2.0.0
statamic/eloquent-driver: 4.14.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```
