### ISSUE TITLE
Recursive Link loop

### ISSUE THREAD

**Issue by ScottPenhall98** [statamic/eloquent-driver#348]
### Bug description

If you are to create a Link field on Entry A that links to Entry B, then on Entry B make a link to Entry A, you get either a never ending save, or a timeout error.

Just to double check this bug I tried replicating this on Statamic core, and it does not seem to be an issue there. We believe it to be an issue only with The Eloquent driver package.

### How to reproduce

Create a Link field on Entry A that links to Entry B, then on Entry B make a link to Entry A

### Environment

```yaml
Environment
Application Name: _
Laravel Version: 10.48.9
PHP Version: 8.3.6
Composer Version: 2.2.22
Environment: local
Debug Mode: ENABLED
URL: _
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.12.0 Solo

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.2.2
statamic/eloquent-driver: 4.8.1

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: file
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```

### Additional details

We are using Lando as a way to run our project, which is a wrapper of docker compose:
name: _
recipe: laravel
services:
  database:
    portforward: 3306
  appserver:
    build_as_root:
      - a2enmod expires headers
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
proxy:
  mailhog:
    - mail.lndo.site
config:
  php: '8.3'
  webroot: public
  database: mysql:8.0
  xdebug: true
