### ISSUE TITLE
Can't export blueprints on Windows

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/eloquent-driver#350]
### Bug description

When you attempt to export blueprints & fieldsets on Windows, an exception is thrown:

```
PS C:\Users\Duncan\Herd\sitename> php please eloquent:export-blueprints

0/70 [>---------------------------] 0%

ErrorException

file_put_contents(C:/Users/Duncan/Herd/sitename/resources/blueprints/C:/xampp/htdocs/laravel-projects/sitename/resources/blueprints/assets/assets.yaml): Failed to open stream: No such file or directory

at vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:204

200▕ * @return int|bool
201▕ */
202▕ public function put($path, $contents, $lock = false)
203▕ {
➜ 204▕ return file_put_contents($path, $contents, $lock ? LOCK_EX : 0);
205▕ }
206▕
207▕ /**
208▕ * Write the contents of a file, replacing it atomically if it already exists.

1 vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:204
2 vendor\statamic\cms\src\Filesystem\AbstractAdapter.php:29

Illuminate\Filesystem\Filesystem::put("C:/Users/Duncan/Herd/sitename/resources/blueprints/C:/xampp/htdocs/laravel-projects/sitename/resources/blueprints/assets/assets.yaml", "title: Asset
```

After some digging, it looks like it has to do with how the blueprint importer imports blueprint namespaces:

![image](https://github.com/user-attachments/assets/fabca084-19d0-4e0b-800f-ddf0964fd0d8)

From a support request. Thanks to @JohnathonKoster with the help troubleshooting.

### How to reproduce

1. Create a fresh Statamic site
2. Move blueprints & fieldsets into the database with `php please install:eloquent-driver`
3. Delete the resources/blueprints directory
4. Then, try to export the blueprints back to flat-files with `php please eloquent:export-blueprints`
5. See the error

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.22.0
PHP Version: 8.3.10
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: eloquent-sandbox.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 3 (The Getaway, Die Flucht, L'Escapade)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.24.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.14.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```
