### ISSUE TITLE
After Taxonomies and terms switch to eloquent driver error occurs

### ISSUE THREAD

**Issue by de-raaf-media** [statamic/eloquent-driver#354]
### Bug description

Illegal offset type in isset or empty. Seems somewhere an object is passed to OffsetExists in Collection?

### How to reproduce

Switch tot eloquent driver for taxonomies and terms. The antlers code then leads to the error "Illegal offset type in isset or empty"

```
{{ categories }}
{{ entries as="category_entries" }}
{{ if category_entries | count > 0 }}
<div class="column is-3">
    <!-- my product -->
    <p>Number of items: {{ category_entries | count }}</p>
</div>
{{ /if }}
{{ /entries }}
{{ /categories }}
```

### Environment

```yaml
Environment
Application Name: x
Laravel Version: 11.20.0
PHP Version: 8.2.20
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: x.test
Maintenance Mode: OFF
Timezone: UTC
Locale: nl

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: daily
Mail: smtp
Queue: database
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.25.0 PRO

Statamic Addons

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
