### ISSUE TITLE
Global set data not exported

### ISSUE THREAD

**Issue by amirul-jb** [statamic/eloquent-driver#357]
### Bug description

Global set data not exported (command export the title only)

### How to reproduce

Create Global and blueprint, then save the data. use export command `php please eloquent:export-globals` when checking the flat file only export title:
![image](https://github.com/user-attachments/assets/b690448d-7856-452a-8465-82cf4eda8939)
![image](https://github.com/user-attachments/assets/c567590a-eb70-4e41-b3cf-0c8644cc965d)

### Environment

```yaml
Environment
Application Name: API
Laravel Version: 11.24.1
PHP Version: 8.2.23
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: api.test.com.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: database
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: database

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.26.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.13.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```
