### ISSUE TITLE
Exporting Entries creates new IDs

### ISSUE THREAD

**Issue by lokmanm** [statamic/eloquent-driver#361]
### Bug description

Hey folks, we are trying to revert a site to Flat Files, and when Exporting Entries new `ids` are created. 

This breaks every relationship within the site.

Is there any way to disable this or do we need to do a PR?

Also Collection Trees are not exported at all, tried a couple of times. 

### How to reproduce

Try to move back to Flat Files from DB and check IDs.

### Environment

```yaml
Application Name: Statamic
Laravel Version: 11.22.0
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.24.0 PRO

Statamic Addons
alt-design/alt-redirect: 1.3.2
doefom/statamic-export: 0.3.2
rias/statamic-data-import: 1.5.0
statamic/eloquent-driver: 4.14.1
statamic/seo-pro: 6.1.1

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```
