### ISSUE TITLE
Folders not appearing when combining file and eloquent

### ISSUE THREAD

**Issue by jymden** [statamic/eloquent-driver#365]
### Bug description

After creating a folder in an asset container, it disappears from the control panel upon refresh unless a file is uploaded into the folder. The folder exists in the file system or on S3 but is not visible in Statamic. This happens with file-based asset containers, even when a .gitkeep file is present.

So in short. You need to have asset containers and assets set to the same driver (file or eloquent) for empty folders to show up in Statamic. 

We have now moved both assets and asset containers to Eloquent, and the issue has been resolved for us. However, we'd like to confirm whether this is a bug or expected behavior.

### How to reproduce

1. Set up Statamic with Eloquent drivers for assets and file driver asset containers, or vice versa,
2. Create a folder in an asset container from the control panel.
3. Refresh the control panel page.
4. Observe that the folder has disappeared from the control panel, but it exists on the disk (e.g., in the file system or on S3).

### Environment

```yaml
Statamic version: 5.31.0
Eloquent Driver Version: 4.15.2
PHP: 8.2.18
WAMP, Azure, Docker

Filesystem Configuration:
Assets stored using Eloquent driver.
Asset containers using file driver.
```
