### ISSUE TITLE
Reorder issue.

### ISSUE THREAD

**Issue by JesperFiltenborg** [statamic/eloquent-driver#368]
### Bug description

Hey,
I've gotten a site for a customer running Statamic 4 and Statamic eloquent driver.
The site has been migrated from a Statamic 3 with Statamic eloquent driver.

The problem i really odd.
I've got a collection using reorder with a max depth of 1.
When i reorder I can see that my database tree is updated but the order on the entries in the database say the same.
If i change the max depth to 0 / blank it works as expected.

I do not know if this is an actual bug or if it's a problem that happened during the migration.

### How to reproduce

I cannot reproduce it on a fresh install, but hope to get some help either in this thread or through a discord call.

### Environment

```yaml
Environment
Application Name: *********
Laravel Version: 10.48.12
PHP Version: 8.2.22
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: *********.ddev.site
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: redis

Statamic
Addons: 6
Antlers: runtime
Sites: 2 (Danish, English)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.58.2 PRO

Statamic Addons
doublethreedigital/duplicator: 4.0.1
jacksleight/statamic-bard-mutator: 2.3.0
pecotamic/sitemap: 1.4.6
statamic/eloquent-driver: 3.4.1

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: file
Navigations: eloquent
Revisions: eloquent
Taxonomies: file
Terms: eloquent
```
