### ISSUE TITLE
Config global set variable model not used in `GlobalVariablesRepository`

### ISSUE THREAD

**Issue by jhhazelaar** [statamic/eloquent-driver#369]
### Bug description

The global set variable model that you define in the config isn't used in de `GlobalVariablesRepository`. We are using our own models to add some global scopes to de queries, but with globals did not work.

### How to reproduce

Create own global set variable model and change config to use this model.  Add scope to variable model. In the debug bar you can't see the added scope in the query.

### Environment

```yaml
Environment
Application Name: Campus Coalitie
Laravel Version: 11.29.0
PHP Version: 8.3.11
Composer Version: 2.7.9
Environment: local
Debug Mode: ENABLED
URL: campus-coalitie.test
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: array
Database: mariadb
Logs: stack / daily
Mail: log
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 2 (EN, NL)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.34.0 PRO

Statamic Addons
eminos/statamic-tabs: 1.2.0
rias/statamic-redirect: 3.8.1
statamic/eloquent-driver: 4.15.2
statamic/seo-pro: 6.3.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: file
Revisions: file
Sites: eloquent
Taxonomies: file
Terms: eloquent
Tokens: eloquent
```
