### ISSUE TITLE
Automatic slug creation from a title

### ISSUE THREAD

**Issue by Ratko-Solaja** [statamic/eloquent-driver#371]
### Bug description

When you install Statamic but use a DB driver. When creating new entries or new taxonomies (anywhere you need a slug that will get generated automatically) it doesn't work.

The problem is that you need to define a locale in Site Settings and only afterwards it will work. If not, axios returns an error in which it clearly says that the language can't be empty.

### How to reproduce

- Start new Statamic installation.
- Select any DB driver (I tried SQLite and MySQL).
- Select to import everything.
- When done, go to Collections -> Pages -> New Entry and type in the title. Slug field won't be populated.

### Environment

```yaml
Environment
Application Name: ****
Laravel Version: 11.29.0
PHP Version: 8.3.13
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: ****.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.35.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.16.0
statamic/importer: 1.0.2

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
