### ISSUE TITLE
Cannot set default sort order on asset containers

### ISSUE THREAD

**Issue by daun** [statamic/eloquent-driver#380]
### Bug description

In a flat-file config, we can add `sort_by` and `sort_dir` keys to an asset container to [set the default order](https://statamic.dev/assets#default-sort-order-in-listings). In Eloquent, those keys seem to be getting removed from the resulting JSON in the database column. Extra keys seem to be stripped rather than left in.

This works in flat-file land:

```yaml
title: Assets
disk: assets
sort_by: basename
sort_dir: desc
```

This doesn't work in the database, as the sort keys are removed and/or ignored:

```json
{
  "allow_uploads": true,
  "allow_downloading": true,
  "allow_moving": true,
  "allow_renaming": true,
  "create_folders": true,
  "search_index": null,
  "source_preset": null,
  "warm_presets": null,
  "validation_rules": [],
  "sort_by": "basename",
  "sort_dir": "desc"
}
```

I would happily switch to storing asset containers as flat files, however issue #365 is still present where newly created folders are not visible in the control panel if they're empty, which makes it hard to fill them in the first place :)

### How to reproduce

- Set up assets and asset containers to be stored in the database
- Manually add a `sort_by` and `sort_dir` key to the JSON `settings` column in the asset container's row
- Browser assets in the control panel, it shouldn't have an effect
- Edit the asset container in the control panel and save
- The manually added sort columns are now removed

### Environment

```yaml
Environment
Application Name: *******
Laravel Version: 11.32.0
PHP Version: 8.3.3
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: *******.test
Maintenance Mode: OFF
Timezone: Europe/Vienna
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 8
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.38.0 PRO

Statamic Addons
daun/statamic-widget-collection-count: 1.2.1
doefom/currency-fieldtype: 1.4.1
jacksleight/statamic-bard-mutator: 3.0.3
jacksleight/statamic-bard-texstyle: 3.3.3
jacksleight/statamic-bonus-routes: 0.3.2
statamic-rad-pack/mailchimp: 5.2.2
statamic/eloquent-driver: 4.17.0
stillat/relationships: 2.2.1

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: eloquent
Navigations: file
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: eloquent
```
