### ISSUE TITLE
Changing a term's slug creates a duplicate term instead of updating the existing one

### ISSUE THREAD

**Issue by daun** [statamic/eloquent-driver#383]
### Bug description

Changing the slug of a taxonomy term results in a new term being created in the database. The old term isn't removed, resulting in duplicate terms with different slugs.

I first assumed this to be related to the [issues with outdated Stache entries](https://github.com/statamic/cms/issues/10938), but this is specific to the Eloquent implementation. The database query is [looking for the new slug](https://github.com/statamic/eloquent-driver/blob/master/src/Taxonomies/Term.php#L77), not finding it, and creating a new term. A simple check for an existing old slug should do the trick here.

### How to reproduce

- Create a new taxonomy (`tags`)
- Create a new term
- Edit the term, updating just the slug
- Return to the list of terms
- There are now two terms, one with the old and one with the new slug

### Environment

```yaml
Environment
Application Name: *******
Laravel Version: 11.32.0
PHP Version: 8.3.3
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: *******.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.38.0 Solo

Statamic Addons
statamic/eloquent-driver: 4.17.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: file
```
