### ISSUE TITLE
BadMethodCallException: Undefined Method 'toModel()' in Statamic Forms Export Command

### ISSUE THREAD

**Issue by emran-alhaddad** [statamic/eloquent-driver#388]
### Bug description

Running the command php please eloquent:export-forms results in a `BadMethodCallException. The error message indicates an undefined method: Statamic\Forms\Submission::toModel()`.

What did you expect to happen?
The forms should be exported successfully without any errors.

Error Output:

```
BadMethodCallException 

Call to undefined method Statamic\Forms\Submission::toModel()

at vendor/statamic/cms/src/Data/HasAugmentedInstance.php:133
    129▕         if (Compare::isQueryBuilder($value)) {
    130▕             return $value;
    131▕         }
    132▕ 
  ➜ 133▕         throw new BadMethodCallException(sprintf('Call to undefined method %s::%s()', static::class, $method));
    134▕     }
    135▕ 
    136▕     #[\ReturnTypeWillChange]
    137▕     public function offsetGet($key)

      +24 vendor frames 

  25  please:18
      Illuminate\Foundation\Application::handleCommand()
```

### How to reproduce

1. Navigate to your project directory.
2. Run the following command: `php please eloquent:export-forms`
3. Observe the BadMethodCallException error.

### Environment

```yaml
Environment
Application Name: ****
Laravel Version: 11.34.2
PHP Version: 8.2.22
Composer Version: 2.5.5
Environment: production
Debug Mode: ENABLED
URL: ***
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 2 (Arabic, English)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.42.0 PRO

Statamic Addons
isaadsalman/headless-refresh: 1.0.0
ndx/statamic-bard-color-picker: 2.0.0
statamic/eloquent-driver: 4.19.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```
