### ISSUE TITLE
Form submission IDs are being incorrectly rounded causing submissions to be inaccessible.

### ISSUE THREAD

**Issue by finnjsmith** [statamic/eloquent-driver#394]
### Bug description

Form submissions IDs contain a unique decimal value, e.g. 1734822720.4899. When using eloquent driver for submissions, the ID column is stored as a `float` datatype. This is proving to be too inaccurate (I'm using MYSQL 8 so unsure if this is a problem on other versions), and it is rounding to a set number of significant figures, e.g 1733830000. The rounding error is preventing form submissions from being accessed in the control panel, causing "Submission not found" to be displayed. See details about floating point accuracy in the MYSQL docs [here](https://dev.mysql.com/doc/refman/8.4/en/floating-point-types.html).

In order to fix this, I've manually changed my database type to a `VARCHAR(255)` datatype in order to preserve the ID value without rounding which I would recommend to be changed in the repository too (another datatype such as DECIMAL may also work).

### How to reproduce

- Use eloquent driver for form submissions
- Create a form
- Submit a submission to the form

### Environment

```yaml
Environment
Application Name: REDACTED
Laravel Version: 11.37.0
PHP Version: 8.3.15
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: REDACTED.local
Maintenance Mode: OFF
Timezone: UTC
Locale: en
MySQL Version: 8.0.40

Cache
Config: NOT CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 13 (International, Australia, Belgium, and 10 more)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.45.1 PRO

Statamic Addons
alt-design/alt-seo: 1.2.2
anakadote/statamic-recaptcha: 1.0.16
rias/statamic-redirect: 3.9.1
statamic/eloquent-driver: 4.19.1
transformstudios/review: 5.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: file
Global Variables: eloquent
Navigation Trees: file
Navigations: file
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: file
```
