### ISSUE TITLE
Custom tests failing due to missing eloquent driver table

### ISSUE THREAD

**Issue by joshtaylordev** [statamic/eloquent-driver#402]
### Bug description

I'm trying to run a basic feature test:
```
public function test_example(): void
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }
```

But it's failing with:
`General error: 1 no such table: asset_containers (Connection: sqlite, SQL: select * from "asset_containers")`

It seems to be stemming from the eloquent driver, as if I change the `asset_containers` driver to `file` in the eloquent-driver config the error doesn't appear.

### How to reproduce

Add a new Test and run the test:
```
<?php

namespace Tests\Feature;

use Tests\TestCase;

class TestTest extends TestCase
{

    /**
     * A basic feature test example.
     */
    public function test_example(): void
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }
}


```

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Shorefield
Laravel Version: 11.44.0
PHP Version: 8.3.16
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
URL: shorefield.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.49.0 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.4.1
ndx/statamic-bard-color-picker: 2.0.1
statamic-rad-pack/runway: 7.14.0
statamic/eloquent-driver: 4.20.0
studio1902/statamic-peak-browser-appearance: 3.6.1
studio1902/statamic-peak-seo: 8.19.1
studio1902/statamic-peak-tools: 6.7.1

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: file
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: eloquent
```
