### ISSUE TITLE
Fieldsets of addons do not get imported

### ISSUE THREAD

**Issue by faustbrian** [statamic/eloquent-driver#406]
### Bug description

I opened issue https://github.com/aerni/statamic-advanced-seo/issues/195 but it seems like this is an issue with the Eloquent Driver. Whenever fieldsets are being imported it only imports the ones that Statamic exposes but not the ones that are registered by addons.

We currently work around this by leaving fieldsets set to `file` and everything else being set to `eloquent` but we would prefer to move everything into the database.

### How to reproduce

Install the Eloquent Driver and e.g. https://github.com/aerni/statamic-advanced-seo and try to import fieldsets.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.44.1
PHP Version: 8.3.17
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: statamic.test/fi
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.6.1

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.13.0
PHP SDK Version: 4.10.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 5
Sites: 6 (Eesti, Suomi, Suomi (Englanti), and 3 more)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.50.0 PRO

Statamic Addons
aerni/advanced-seo: 2.12.0
marcorieser/statamic-livewire: 4.1.0
mitydigital/sitemapamic: 3.2.0
spatie/statamic-responsive-images: 5.2.2
statamic/eloquent-driver: 4.20.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```
