### ISSUE TITLE
Form submissions primary keys are stored as integers, while populated from Statamic as a timestamp string

### ISSUE THREAD

**Issue by Boefjim** [statamic/eloquent-driver#410]
### Bug description

Statamic CMS populates the primary key (ID) of form submissions with `str_replace(',', '.', microtime(true))`.
The migration provided by the Eloquent driver creates a Laravel `id` column instead (which creates a `unsigned bigint` column).
This causes the IDs to be rounded to their nearest integer when storing the form submissions.
Today this caused a problem for us, because 2 submissions were received within the same second, causing this rounding to result in the same ID.

Can this be adjusted so that the column uses a timestamp (with microseconds), or a string instead?

### How to reproduce

1. Create sample Statamic CMS project with the Eloquent Driver package installed & enabled
2. Create a form
3. Submit the form twice quickly
4. Get a duplicate primary key error for the second submission

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 10.48.25
PHP Version: 8.2.27
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 3.8.2
PHP SDK Version: 3.22.1
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 4
Sites: 26 (Europe, Belgium (FR), Belgium (NL), and 23 more)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.41.0 PRO

Statamic Addons
mitydigital/statamic-two-factor: 2.3.0
statamic/eloquent-driver: 4.18.0
stoffelio/statamic-404-logger: 1.1.0
superinteractive/statamic-super-link: 1.0.1

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: file
Navigations: eloquent
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: file
```
