### ISSUE TITLE
Is it necessary to limit terms to those that are used?

### ISSUE THREAD

**Issue by petemolinero** [statamic/eloquent-driver#421]
### Bug description

In `TermQueryBuilder`, there is a section where returned terms are limited to those that are actually used by entries:

https://github.com/statamic/eloquent-driver/blob/40e99ad71c50f1f93228dee7e39e4b78d9b60591/src/Taxonomies/TermQueryBuilder.php#L237-L243

My question is: is this necessary, and/or what benefit does this provide? In my use case where I have a mere `699` rows in my `taxonomy_terms` table, the above `whereExists` adds 2-3 seconds to the overall query time.

-------

**With whereExists (2.15 seconds)**

<img width="816" alt="Image" src="https://github.com/user-attachments/assets/f6955a51-1956-46f4-a779-b88138354339" />

------

**Without whereExists (3.12 milliseconds)**

<img width="818" alt="Image" src="https://github.com/user-attachments/assets/1cd4e0f4-9052-491d-8ef1-5fea3ae4fdd4" />

-------

I do think this is better than it's predecessor: doing it via `->map()`. But I'm just wondering if it originally came into existence with the idea that by limiting to terms that actually appear on posts it'd be saving some query time, when in fact it astronomically increases it?

At minimum, I wonder it might be worth creating an option to disable this? As it stands I'm having to do a workaround to avoid ever doing things like this, since it encounters that multi-second slowdown.

```
{{ foreach:posts as="post" }}
<ul>
  {{ post.tags }}
  <li>{{ title }}</li>
  {{ /post.tags }}
</ul>
{{ /foreach:posts }}
```

### How to reproduce

1. Create 500+ taxonomy terms
2. Create an entry with the following antlers code:

```
{{ collection:posts as="posts" id:is="123" }}
 {{ foreach:posts as="post" }}
 <ul>
    {{ post.tags }}
    <li>{{ title }}</li>
    {{ /post.tags }}
 </ul>
 {{ /foreach:posts }}
{{ /collection:posts }}
```

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Medbridge
Laravel Version: 12.8.1
PHP Version: 8.4.5
Composer Version: 2.8.8
Environment: development
Debug Mode: ENABLED
URL: --REDACTED--
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis-read-write
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Storage
public/storage: LINKED

Statamic
Addons: 2
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.53.0 PRO

Statamic Addons
rias/statamic-redirect: 3.9.3
statamic/eloquent-driver: 4.21.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: file
```
