### ISSUE TITLE
`InvalidArgumentException` thrown when site handle matches condition operator

### ISSUE THREAD

**Issue by SteveEdson** [statamic/eloquent-driver#424]
### Bug description

I installed the eloquent driver, but immediately got an issue when the entries were imported to the database:

![Image](https://github.com/user-attachments/assets/7fadd5d3-863e-415c-9067-981df23a3e74)

I've spent some time diving into this and I've found the issue, but i'm not quite sure why.

In `src/Structures/CollectionStructure.php`, line 78, the following breaks:
```php
$thisCollectionsEntries = $this->collection()->queryEntries()
            ->where('site', $locale)
            ->pluck('id');
```

However changing it to:
```php
$thisCollectionsEntries = $this->collection()->queryEntries()
            ->where('site', '=', $locale)
            ->pluck('id');
```

Resolves the issue. It seems to think the `$locale` is the operator, which doesn't work. Is this a bug in the core, or something in my config? If it was truly broken, everyone would be having this issue, so i'm not sure why it's just me?

### How to reproduce

I just installed the eloquent driver and imported collections and entries.

### Logs

The following trace is more useful:

![Image](https://github.com/user-attachments/assets/04c3c532-0920-4bbc-bdde-441992f1b834)

### Environment

```yaml
Environment
Application Name: XXXX
Laravel Version: 11.44.7
PHP Version: 8.3.20
Composer Version: 2.8.8
Environment: local
Debug Mode: ENABLED
URL: XXXX.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 26 (Belgium / Dutch, Belgium / French, Denmark / Danish, and 23 more)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.55.0 PRO

Statamic Addons
alt-design/alt-redirect: 1.6.3
mitydigital/sitemapamic: 3.2.0
statamic/eloquent-driver: 4.21.1
statamic/ssg: 3.1.1

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: file
Terms: file
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
I've moved this to the `eloquent-driver` repo.

Can you provide your `config/statamic/eloquent-driver.php` config, along with your `resources/sites.yaml` file?

**Comment by SteveEdson** [comment]
Minimal config to reproduce (only happens with entries collection being eloquent, the rest are fine):

```php
<?php

return [

    'connection' => env('STATAMIC_file_CONNECTION', ''),
    'table_prefix' => env('STATAMIC_file_PREFIX', ''),

    'asset_containers' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Assets\AssetContainerModel::class,
    ],

    'assets' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Assets\AssetModel::class,
        'asset' => \Statamic\Eloquent\Assets\Asset::class,
    ],

    'blueprints' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Fields\BlueprintModel::class,
        'namespaces' => 'all',
    ],

    'collections' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Collections\CollectionModel::class,
        'update_entry_order_queue' => 'default',
        'update_entry_order_connection' => 'default',
    ],

    'collection_trees' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Structures\TreeModel::class,
        'tree' => \Statamic\Eloquent\Structures\CollectionTree::class,
    ],

    'entries' => [
        'driver' => 'eloquent',
        'model' => \Statamic\Eloquent\Entries\UuidEntryModel::class,
        'entry' => \Statamic\Eloquent\Entries\Entry::class,
        'map_data_to_columns' => false,
    ],

    'fieldsets' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Fields\FieldsetModel::class,
    ],

    'forms' => [
        'driver' => 'file',
        'model'  => \Statamic\Eloquent\Forms\FormModel::class,
    ],

    'form_submissions' => [
        'driver' => 'file',
        'model'  => \Statamic\Eloquent\Forms\SubmissionModel::class,
    ],

    'global_sets' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Globals\GlobalSetModel::class,
    ],

    'global_set_variables' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Globals\VariablesModel::class,
    ],

    'navigations' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Structures\NavModel::class,
    ],

    'navigation_trees' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Structures\NavTree::class,
        'tree' => \Statamic\Eloquent\Structures\NavTree::class,
    ],

    'revisions' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Revisions\RevisionModel::class,
    ],

    'taxonomies' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Taxonomies\TaxonomyModel::class,
    ],

    'terms' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Taxonomies\TermModel::class,
    ],

    'tokens' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Tokens\TokenModel::class,
    ],

    'sites' => [
        'driver' => 'file',
        'model' => \Statamic\Eloquent\Sites\SiteModel::class,
    ],
];

```

Sites yaml:

```yaml
engb:
  name: 'United Kingdom / English'
  locale: en_GB
  url: /en/gb
  attributes:
    frontend_name: 'English UK'
    country: 'United Kingdom'
    continent: Europe
    order: '1'
  lang: en_GB
nl:
  name: 'Belgium / Dutch'
  locale: nl_NL
  url: /be/nl/
  attributes:
    frontend_name: Dutch
    country: Belgium
    continent: Europe
    order: '20'
  lang: nl_NL
be:
  name: 'Belgium / French'
  locale: fr_BE
  url: /be/fr/
  attributes:
    frontend_name: French
    country: Belgium
    continent: Europe
    order: '30'
  lang: fr_BE
dk:
  name: 'Denmark / Danish'
  url: /dk/dk
  locale: dk_DA
  lang: dk_DA
  attributes:
    frontend_name: Danish
    country: Denmark
    continent: Europe
    order: '50'
ee:
  name: 'Estonia / Estonian'
  url: /ee/et
  locale: ee_ET
  lang: ee_ET
  attributes:
    frontend_name: Estonian
    country: Estonia
    continent: Europe
    order: '60'
fi:
  name: 'Finland / Finnish'
  url: /fi/fi
  locale: fi_Fi
  lang: fi_Fi
  attributes:
    frontend_name: Finnish
    country: Finland
    continent: Europe
    order: '70'
fr:
  name: 'France / French'
  locale: fr_FR
  url: /fr/fr/
  attributes:
    frontend_name: French
    country: France
    continent: Europe
    order: '80'
  lang: fr_FR
de:
  name: 'Germany / German'
  locale: de_DE
  url: /de/de/
  attributes:
    frontend_name: German
    country: Germany
    continent: Europe
    order: '90'
  lang: de_DE
deen:
  name: 'Germany / English'
  locale: en_DE
  url: /de/en/
  attributes:
    frontend_name: English
    country: Germany
    continent: Europe
    order: '100'
  lang: en_DE
is:
  name: 'Iceland / Icelandic'
  url: /is/is
  locale: is_IS
  lang: is_IS
  attributes:
    frontend_name: Icelandic
    country: Iceland
    continent: Europe
    order: '110'
ie:
  name: 'Ireland / English'
  locale: ie_IE
  url: /ie/en/
  attributes:
    frontend_name: English
    country: Ireland
    continent: Europe
    order: '120'
  lang: ie_IE
it:
  name: 'Italy / Italian'
  locale: it_IT
  url: /it/it/
  attributes:
    frontend_name: Italian
    country: Italy
    continent: Europe
    order: '130'
  lang: it_IT
iten:
  name: 'Italy / English'
  locale: en_IT
  url: /it/en/
  attributes:
    frontend_name: English
    country: Italy
    continent: Europe
    order: '140'
  lang: en_IT
lv:
  name: 'Latvia / Latvian'
  url: /lv/lv
  locale: lv_LV
  lang: lv_LV
  attributes:
    frontend_name: Latvian
    country: Latvia
    continent: Europe
    order: '150'
lt:
  name: 'Lithuania / Lithuanian'
  url: /lt/lt
  locale: lt_LT
  lang: lt_LT
  attributes:
    frontend_name: Lithuanian
    country: Lithuania
    continent: Europe
    order: '160'
'no':
  name: 'Norway / Norwegian'
  locale: no_NO
  url: /no/no/
  attributes:
    frontend_name: Norwegian
    country: Norway
    continent: Europe
    order: '170'
  lang: no_NO
pl:
  name: 'Poland / Polish'
  locale: pl_PL
  url: /pl/pl/
  attributes:
    frontend_name: Polish
    country: Poland
    continent: Europe
    order: '180'
  lang: pl_PL
plen:
  name: 'Poland / English'
  locale: en_PL
  url: /pl/en/
  attributes:
    frontend_name: English
    country: Poland
    continent: Europe
    order: '190'
  lang: en_PL
pt:
  name: 'Portugal / Portuguese'
  locale: pt_PT
  url: /pt/pt/
  attributes:
    frontend_name: Portuguese
    country: Portugal
    continent: Europe
    order: '200'
  lang: pt_PT
pten:
  name: 'Portugal / English'
  locale: en_PT
  url: /pt/en/
  attributes:
    frontend_name: English
    country: Portugal
    continent: Europe
    order: '210'
  lang: en_PT
es:
  name: 'Spain / Spanish'
  locale: es_ES
  url: /es/es/
  attributes:
    frontend_name: Spanish
    country: Spain
    continent: Europe
    order: '220'
  lang: es_ES
se:
  name: 'Sweden / Swedish'
  locale: se_SE
  url: /se/se/
  attributes:
    frontend_name: Swedish
    country: Sweden
    continent: Europe
    order: '230'
  lang: se_SE
seen:
  name: 'Sweden / English'
  locale: en_SE
  url: /se/en/
  attributes:
    country: Sweden
    frontend_name: English
    continent: Europe
    order: '240'
  lang: se_EN
tr:
  name: 'Turkey / Turkish'
  locale: tr_TR
  url: /tr/tr/
  attributes:
    frontend_name: Turkish
    country: Turkey
    continent: 'Middle East'
    order: '250'
  lang: tr_TR
gr:
  name: 'Greece / Greek'
  url: /gr/el
  locale: gr_EL
  lang: gr_EL
  attributes:
    frontend_name: Greek
    country: Greece
    continent: Europe
    order: '260'
gren:
  name: 'Greece / English'
  url: /gr/en/
  locale: en_GB
  lang: en_GB
  attributes:
    frontend_name: English
    country: Greece
    continent: Europe
    order: '270'

```
