### ISSUE TITLE
Global Set Variables Persist in Both DB and Files Despite Config

### ISSUE THREAD

**Issue by mcrepaldi** [statamic/eloquent-driver#428]
### Bug description

I have configured the Eloquent driver with the following setup:

- Global Sets are set to use files
- Global Variables are set to use Eloquent

This configuration works for retrieving values. However, when saving values to the Global Sets, the data is being stored in both locations:
 
- In the file: `/content/globals/mycoolglobalset.yaml`
- In the database: `global_set_variables` table

At runtime, the values are only read from the database, which means the file becomes redundant and creates unnecessary changes in version control (dirty Git state).

Expected Behavior:
When Global Variables are configured to use the Eloquent driver, values should be stored only in the database and not persisted to YAML files.

### How to reproduce

1. Configure `eloquent-driver.php` with the following settings:

```
'global_sets' => [
    'driver' => 'file',
    'model' => \Statamic\Eloquent\Globals\GlobalSetModel::class,
],

'global_set_variables' => [
    'driver' => 'eloquent',
    'model' => \Statamic\Eloquent\Globals\VariablesModel::class,
],
```

2. Create a Global Set named `mycoolglobalset`. This will result in:

- A configuration file at `/content/globals/mycoolglobalset.yaml`
- A corresponding blueprint for the global set
- An initial record in the `global_set_variables` database table

3. Add a field to the blueprint and save a value.

4. Observe that:
- The value is saved to **both** `/content/globals/mycoolglobalset.yaml` and the `global_set_variables` table

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Laravel
Laravel Version: 12.15.0
PHP Version: 8.4.7
Composer Version: 2.8.9
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: sqlite
Logs: stack / single
Mail: log
Queue: database
Session: database

Storage
public/storage: NOT LINKED

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.56.0 Solo

Statamic Addons
statamic/eloquent-driver: 4.21.1

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```
