### ISSUE TITLE
Taxonomy Scope to the right collections fails after Update to latest Version

### ISSUE THREAD

**Issue by HannesEURESA** [statamic/eloquent-driver#437]
### Bug description

All Entries within one Taxonomy term are gone after update to the latest Version.
Moving back to 4.22.0 fixes this issue.

So If i got to the index page of a term, there are all Entries gone.

### How to reproduce

Choosing within a collection 1 Taxonomy, redirecting to the index page of this term where all the entries are listed, but there are shown 0 entries. 

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: 
Laravel Version: 11.45.1
PHP Version: 8.3.16
Composer Version: 2.8.5
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: mysql
Logs: stack / single
Mail: ses
Queue: database
Session: database

Locales
Installed: cs, da, de, en, nb, nl, nn
LaravelLang\Lang\Plugin: 15.21.0
Locales Version: 2.10.0
Protected: de, en
Publisher Version: 16.6.0

Livewire
Livewire: v3.6.3

Statamic
Addons: 8
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: half
Version: 5.57.0 PRO

Statamic Addons
marcorieser/statamic-live-search: 3.0.0
marcorieser/statamic-livewire: 4.5.1
rias/statamic-redirect: 3.10.9
statamic/eloquent-driver: 4.2.0
stillat/antlers-components: 2.6.0
studio1902/statamic-peak-browser-appearance: 3.6.1
studio1902/statamic-peak-seo: 8.23.0
studio1902/statamic-peak-tools: 7.3.1

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: file
Global Variables: file
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```
