### ISSUE TITLE
GlobalVariablesSaved event not fired when using Eloquent driver

### ISSUE THREAD

**Issue by swen4** [statamic/eloquent-driver#441]
### Bug description

On one of our client's sites, we ran into an issue where the Statamic's static cache invalidation wasn't working as expected. More specifically, any "globals" invalidation rules we configured didn't seem to work at all.

After some debugging, I found out that the `GlobalVariablesSaved` event does not seem to fire at all when eloquent driver is used.

Switching back to the "file" driver triggered the event again as normal.

### How to reproduce

- Configure eloquent-driver.php to use eloquent for `global_sets` and `global_set_variables`.
- Create a listener for the GlobalVariablesSaved that logs to debug.log.
- Save any globals page, nothing shows up in logs.
- Run `php please eloquent:export-globals` to export the globals to files.
- Revert `global_sets` and `global_set_variables` in eloquent-driver.php to "file".
- Save any globals page, now the event is shown in logs.

In AppServerProvider.php's boot method:

```
Event::listen(GlobalVariablesSaved::class, TestGlobals::class);
```

Listener `TestGlobals.php`

```
<?php

namespace App\Listeners;

use Illuminate\Support\Facades\Log;
use Statamic\Events\GlobalVariablesSaved;

class TestGlobals
{
    public function __construct() {}

    public function handle(GlobalVariablesSaved $event): void
    {
        Log::info("Event", ['event' => $event]);
    }
}
```

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.45.1
PHP Version: 8.3.19
Composer Version: 2.8.6
Environment: staging
Debug Mode: ENABLED
URL: wnl.test
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: nl

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.6.3

Sentry
Enabled: MISSING DSN
Environment: staging
Laravel SDK Version: 4.14.0
PHP SDK Version: 4.11.1
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 10
Sites: 1
Stache Watcher: Enabled
Static Caching: full
Version: 5.57.0 PRO

Statamic Addons
alt-design/alt-redirect: 1.6.3
duncanmcclean/static-cache-manager: 4.0.1
marcorieser/statamic-livewire: 4.5.1
maveio/statamic-mave: 1.0.2
statamic-rad-pack/meilisearch: 3.4.0
statamic-rad-pack/runway: 7.14.0
statamic/eloquent-driver: 4.23.2
statamic/seo-pro: 6.7.0
stillat/relationships: 2.2.1
superinteractive/statamic-super-link: 2.0.1

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: file
Navigations: file
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: eloquent
```
