### ISSUE TITLE
(n+1) performance issue using assets

### ISSUE THREAD

**Issue by Jubeki** [statamic/eloquent-driver#445]
### Bug description

Hey everyone,

I found a (n+1) performance issue in the handling of assets while using the eloquent driver.

The problem occurs, when you have multiple assets on the same field (in my example repo there are 3 assets).
This will result in 4 queries, where in my opinion the first query should be enough to fetch all assets (the other queries are fired to check if the assets meta exists, though they are already fetched in the first query).

```sql
select * from "assets_meta" where "container" = 'assets' and "path" in ('352-200x300.jpg', '990-200x300.jpg', '666-200x300.jpg')
select count(*) as aggregate from "assets_meta" where ("container" = 'assets' and "folder" = '/' and "basename" = '352-200x300.jpg')
select count(*) as aggregate from "assets_meta" where ("container" = 'assets' and "folder" = '/' and "basename" = '990-200x300.jpg')
select count(*) as aggregate from "assets_meta" where ("container" = 'assets' and "folder" = '/' and "basename" = '666-200x300.jpg')
```

How we encountered this issue:
We had a field with more than 20 assets, and saw degraded performance, so we dove deeper and saw n+a queries.

The Problem lies in `Statamic\Eloquent\Assets\Asset`, where the exists method is called by statamic:

```php
public function exists()
{
    return $this->existsOnDisk || $this->metaExists();
}

public function metaExists()
{
    return Blink::once('eloquent-asset-meta-exists-'.$this->id(), function () {
        return app('statamic.eloquent.assets.model')::query()
            ->where([
                'container' => $this->containerHandle(),
                'folder' => $this->folder(),
                'basename' => $this->basename(),
            ])->count() > 0;
    });
}
```

### How to reproduce

1. Setup a fresh statamic application which uses the eloquent-driver.
2. Create an Assets Field in the Page blueprint (allow multiple assets)
3. Upload multiple assets to the home page
4. Render the assets on the home page
5. Log all queries in the AppServiceProvider:

```php
DB::listen(function(QueryExecuted $query) {
    Log::debug($query->toRawSql());
});
```

6. Go to the home page to execute queries.
7. Take a look at `storage/logs/laravel.log` to see all queries.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.17.0
PHP Version: 8.3.22
Composer Version: 2.8.9
Environment: local
Debug Mode: ENABLED
URL: statamic-multiple-assets-query-issue.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.57.0 Solo

Statamic Addons
statamic/eloquent-driver: 4.23.4

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```
