### ISSUE TITLE
In version 4.23.3, there is a media library error

### ISSUE THREAD

**Issue by fajriyan** [statamic/eloquent-driver#450]
### Bug description

When I create a new project and select a database instead of a flat file, in version 4.23.3 the media library becomes error, I cannot create folders, I cannot upload files, there is a duplicate file warning even though there are no duplicate files at all (when I create a folder it appears, then when I reload the folder it disappears, in the vscode file there is a folder but in the database it is empty).

<img width="1445" alt="Image" src="https://github.com/user-attachments/assets/b798e023-2d4b-4e66-935f-8ad30b981bc1" />

video screen record :
https://github.com/user-attachments/assets/077f3b4d-691e-45d0-9e3c-8864028d94ca

When I downgraded to 4.23.2, everything returned to normal.

### How to reproduce

1. I installed Statamic and selected a database.
2. I uploaded a new file, but got a warning about duplicate files.
3. I created a folder, but when I reloaded the page, it disappeared.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 12.18.0
PHP Version: 8.3.20
Composer Version: 2.8.8
Environment: local
Debug Mode: ENABLED
URL: bnpt-site.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Livewire
Livewire: v3.6.3

Statamic
Addons: 2
Sites: 2 (Indonesia, English)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.56.0 PRO

Statamic Addons
marcorieser/statamic-livewire: 4.5.1
statamic/eloquent-driver: 4.24.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```
