### ISSUE TITLE
Empty folders are not visible or appear to be missing in Assets

### ISSUE THREAD

**Issue by amamboni** [statamic/eloquent-driver#453]
### Bug description

I am aware that similar issues have been reported previously (e.g., statamic/cms#3722 and statamic/cms#4235), however, the problem still persists.

Although the folder is successfully created in local storage and can be accessed directly via URL (e.g., /cp/assets/browse/assets/sample), it does not appear in the interface. Furthermore, attempting to create a folder with the same name results in an error stating, "Directory already exists."

Based on my observations, this behavior affects all empty folders, even those that previously contained files. Additionally, if an empty folder is nested within another empty folder, it also fails to display.

### How to reproduce

1. Go to Assets
2. Create a folder
3. Refresh the page or navigate to another page and then return

The folder is missing, and clearing caches or enabling the Stache watcher to auto does not seem to resolve the issue.

### Logs

```shell

```

### Environment

```yaml
Environment
Laravel Version: 12.12.0
PHP Version: 8.3.21
Composer Version: 2.8.9
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Storage
public/storage: LINKED

Statamic
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.57.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI
