### ISSUE TITLE
`AssetContainer@asset()` doesn't set the `model` property on `Asset` class

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/eloquent-driver#456]
### Bug description

When you call `$assetContainer->asset($path)` using the path of an existing asset, the returned `Asset` class is missing the `model` property.

This leads to an error when you try update the asset's metadata because it tries to create a new row in the database, rather than updating the existing row.

You can workaround using `AssetContainer@assets()` which queries the database and _does_ set the `model` property:

```php
$asset = $assetContainer->assets()->where('path', 'existing-asset.jpg')->first();

$asset->model; // \Statamic\Eloquent\Assets\AssetModel
```

### How to reproduce

1. Install the Eloquent Driver
2. Move assets to the database
3. Upload an asset
4. Attempt to lookup the asset using the `AssetContainer@asset()` method:

```php
use Statamic\Facades\AssetContainer;

$asset = $AssetContainer::find('images')->asset('existing-asset.jpg');

$asset->model; // "null"
```

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Site Name
Laravel Version: 12.18.0
PHP Version: 8.4.8
Composer Version: 2.8.9
Environment: local
Debug Mode: ENABLED
URL: site-name.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.57.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.25.1

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: file
Tokens: file
```
