### ISSUE TITLE
Publish entry changes his order on collection tree

### ISSUE THREAD

**Issue by eduardocastro-loba** [statamic/eloquent-driver#458]
### Bug description

I have two childs on a category, everytime I edit the first one and publish, it jump to last. 
Same happends if I have more items. Example: if I have 5 items and edit the third one, when published jumps to last.

This is very annoying for client.
Can someone help?

https://github.com/user-attachments/assets/92c43baf-ca96-449b-bcb6-5c917203a6c9

### How to reproduce

Collection yaml
```title: Coleções
sites:
  - pt
  - en
  - fr
  - es
  - de
propagate: false
template: default
layout: layout
mount: 88
revisions: true
route: '{{ depth == 1 ?= mount }}/{{ parent_uri }}/{{ slug }}'
date: true
sort_dir: asc
default_status: draft
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: 'https://domain.com/preview/{{ locale }}/{{ slug }}'
    refresh: true
origin_behavior: root
structure:
  root: false
  max_depth: 2
```

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: FAMO
Laravel Version: 12.16.0
PHP Version: 8.4.7
Composer Version: 2.8.8
Environment: local
Debug Mode: ENABLED
URL: famo.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 2
Sites: 5 (Português, English, Français, Español, Deutsch)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.56.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.23.0
webographen/statamic-admin-log: 1.1.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: file
Revisions: file
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI
